//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SpecParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class SpecParserParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SINGLE_LINE_DOC_COMMENT=1, DELIMITED_DOC_COMMENT=2, SINGLE_LINE_COMMENT=3, 
		DELIMITED_COMMENT=4, CALLING_CONVENTION=5, ADD_AFTER_USINGS=6, CLASS_NAME=7, 
		CODE=8, COMPILER_OPTION=9, DLLIMPORT=10, EXCLUDE=11, IMPORT_FILE=12, NAMESPACE=13, 
		PASS=14, PREFIX_STRIP=15, TEMPLATE=16, USING=17, REWRITE=18, EQ=19, SEMI=20, 
		OR=21, STAR=22, PLUS=23, DOT=24, DOLLAR=25, OPEN_RE=26, CLOSE_RE=27, OPEN_PAREN=28, 
		CLOSE_PAREN=29, OPEN_KLEENE_STAR_PAREN=30, CLOSE_KLEENE_STAR_PAREN=31, 
		OPEN_BRACKET_NOT=32, OPEN_BRACKET=33, CLOSE_BRACKET=34, MINUS=35, LCURLY=36, 
		LANG=37, StringLiteral=38, ID=39, WS=40, RCURLY=41, OTHER=42, RANG=43, 
		OTHER_ANG=44;
	public const int
		RULE_spec = 0, RULE_items = 1, RULE_using = 2, RULE_import_file = 3, RULE_compiler_option = 4, 
		RULE_template = 5, RULE_rexp = 6, RULE_simple_rexp = 7, RULE_basic_rexp = 8, 
		RULE_star_rexp = 9, RULE_plus_rexp = 10, RULE_elementary_rexp = 11, RULE_group_rexp = 12, 
		RULE_basic = 13, RULE_simple_basic = 14, RULE_kleene_star_basic = 15, 
		RULE_id_or_star_or_empty = 16, RULE_more = 17, RULE_code = 18, RULE_text = 19, 
		RULE_attr = 20, RULE_pass = 21;
	public static readonly string[] ruleNames = {
		"spec", "items", "using", "import_file", "compiler_option", "template", 
		"rexp", "simple_rexp", "basic_rexp", "star_rexp", "plus_rexp", "elementary_rexp", 
		"group_rexp", "basic", "simple_basic", "kleene_star_basic", "id_or_star_or_empty", 
		"more", "code", "text", "attr", "pass"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, "'calling_convention'", "'add_after_usings'", 
		"'class_name'", "'code'", "'compiler_option'", "'dllimport'", "'exclude'", 
		"'import_file'", "'namespace'", "'pass'", "'prefix_strip'", "'template'", 
		"'using'", "'=>'", "'='", "';'", "'|'", "'*'", "'+'", "'.'", "'$'", "'(%'", 
		"'%)'", "'('", "')'", "'(*'", "'*)'", "'[^'", "'['", "']'", "'-'", null, 
		null, null, null, null, "'}}'", null, "']]'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SINGLE_LINE_DOC_COMMENT", "DELIMITED_DOC_COMMENT", "SINGLE_LINE_COMMENT", 
		"DELIMITED_COMMENT", "CALLING_CONVENTION", "ADD_AFTER_USINGS", "CLASS_NAME", 
		"CODE", "COMPILER_OPTION", "DLLIMPORT", "EXCLUDE", "IMPORT_FILE", "NAMESPACE", 
		"PASS", "PREFIX_STRIP", "TEMPLATE", "USING", "REWRITE", "EQ", "SEMI", 
		"OR", "STAR", "PLUS", "DOT", "DOLLAR", "OPEN_RE", "CLOSE_RE", "OPEN_PAREN", 
		"CLOSE_PAREN", "OPEN_KLEENE_STAR_PAREN", "CLOSE_KLEENE_STAR_PAREN", "OPEN_BRACKET_NOT", 
		"OPEN_BRACKET", "CLOSE_BRACKET", "MINUS", "LCURLY", "LANG", "StringLiteral", 
		"ID", "WS", "RCURLY", "OTHER", "RANG", "OTHER_ANG"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SpecParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SpecParserParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SpecParserParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SpecParserParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class SpecContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(SpecParserParser.Eof, 0); }
		public ItemsContext[] items() {
			return GetRuleContexts<ItemsContext>();
		}
		public ItemsContext items(int i) {
			return GetRuleContext<ItemsContext>(i);
		}
		public SpecContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_spec; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterSpec(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitSpec(this);
		}
	}

	[RuleVersion(0)]
	public SpecContext spec() {
		SpecContext _localctx = new SpecContext(Context, State);
		EnterRule(_localctx, 0, RULE_spec);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << COMPILER_OPTION) | (1L << IMPORT_FILE) | (1L << PASS) | (1L << TEMPLATE) | (1L << USING))) != 0)) {
				{
				{
				State = 44; items();
				}
				}
				State = 49;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 50; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ItemsContext : ParserRuleContext {
		public UsingContext @using() {
			return GetRuleContext<UsingContext>(0);
		}
		public Import_fileContext import_file() {
			return GetRuleContext<Import_fileContext>(0);
		}
		public Compiler_optionContext compiler_option() {
			return GetRuleContext<Compiler_optionContext>(0);
		}
		public TemplateContext template() {
			return GetRuleContext<TemplateContext>(0);
		}
		public PassContext pass() {
			return GetRuleContext<PassContext>(0);
		}
		public ItemsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_items; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterItems(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitItems(this);
		}
	}

	[RuleVersion(0)]
	public ItemsContext items() {
		ItemsContext _localctx = new ItemsContext(Context, State);
		EnterRule(_localctx, 2, RULE_items);
		try {
			State = 57;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case USING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 52; @using();
				}
				break;
			case IMPORT_FILE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 53; import_file();
				}
				break;
			case COMPILER_OPTION:
				EnterOuterAlt(_localctx, 3);
				{
				State = 54; compiler_option();
				}
				break;
			case TEMPLATE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 55; template();
				}
				break;
			case PASS:
				EnterOuterAlt(_localctx, 5);
				{
				State = 56; pass();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UsingContext : ParserRuleContext {
		public ITerminalNode USING() { return GetToken(SpecParserParser.USING, 0); }
		public ITerminalNode StringLiteral() { return GetToken(SpecParserParser.StringLiteral, 0); }
		public ITerminalNode SEMI() { return GetToken(SpecParserParser.SEMI, 0); }
		public UsingContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_using; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterUsing(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitUsing(this);
		}
	}

	[RuleVersion(0)]
	public UsingContext @using() {
		UsingContext _localctx = new UsingContext(Context, State);
		EnterRule(_localctx, 4, RULE_using);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59; Match(USING);
			State = 60; Match(StringLiteral);
			State = 61; Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Import_fileContext : ParserRuleContext {
		public ITerminalNode IMPORT_FILE() { return GetToken(SpecParserParser.IMPORT_FILE, 0); }
		public ITerminalNode StringLiteral() { return GetToken(SpecParserParser.StringLiteral, 0); }
		public ITerminalNode SEMI() { return GetToken(SpecParserParser.SEMI, 0); }
		public Import_fileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_import_file; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterImport_file(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitImport_file(this);
		}
	}

	[RuleVersion(0)]
	public Import_fileContext import_file() {
		Import_fileContext _localctx = new Import_fileContext(Context, State);
		EnterRule(_localctx, 6, RULE_import_file);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63; Match(IMPORT_FILE);
			State = 64; Match(StringLiteral);
			State = 65; Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Compiler_optionContext : ParserRuleContext {
		public ITerminalNode COMPILER_OPTION() { return GetToken(SpecParserParser.COMPILER_OPTION, 0); }
		public ITerminalNode StringLiteral() { return GetToken(SpecParserParser.StringLiteral, 0); }
		public ITerminalNode SEMI() { return GetToken(SpecParserParser.SEMI, 0); }
		public Compiler_optionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compiler_option; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterCompiler_option(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitCompiler_option(this);
		}
	}

	[RuleVersion(0)]
	public Compiler_optionContext compiler_option() {
		Compiler_optionContext _localctx = new Compiler_optionContext(Context, State);
		EnterRule(_localctx, 8, RULE_compiler_option);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67; Match(COMPILER_OPTION);
			State = 68; Match(StringLiteral);
			State = 69; Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TemplateContext : ParserRuleContext {
		public ITerminalNode TEMPLATE() { return GetToken(SpecParserParser.TEMPLATE, 0); }
		public RexpContext rexp() {
			return GetRuleContext<RexpContext>(0);
		}
		public ITerminalNode SEMI() { return GetToken(SpecParserParser.SEMI, 0); }
		public TemplateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_template; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterTemplate(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitTemplate(this);
		}
	}

	[RuleVersion(0)]
	public TemplateContext template() {
		TemplateContext _localctx = new TemplateContext(Context, State);
		EnterRule(_localctx, 10, RULE_template);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71; Match(TEMPLATE);
			State = 72; rexp();
			State = 73; Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RexpContext : ParserRuleContext {
		public Simple_rexpContext[] simple_rexp() {
			return GetRuleContexts<Simple_rexpContext>();
		}
		public Simple_rexpContext simple_rexp(int i) {
			return GetRuleContext<Simple_rexpContext>(i);
		}
		public ITerminalNode[] OR() { return GetTokens(SpecParserParser.OR); }
		public ITerminalNode OR(int i) {
			return GetToken(SpecParserParser.OR, i);
		}
		public RexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rexp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterRexp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitRexp(this);
		}
	}

	[RuleVersion(0)]
	public RexpContext rexp() {
		RexpContext _localctx = new RexpContext(Context, State);
		EnterRule(_localctx, 12, RULE_rexp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 75; simple_rexp();
			State = 80;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OR) {
				{
				{
				State = 76; Match(OR);
				State = 77; simple_rexp();
				}
				}
				State = 82;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Simple_rexpContext : ParserRuleContext {
		public Basic_rexpContext[] basic_rexp() {
			return GetRuleContexts<Basic_rexpContext>();
		}
		public Basic_rexpContext basic_rexp(int i) {
			return GetRuleContext<Basic_rexpContext>(i);
		}
		public Simple_rexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simple_rexp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterSimple_rexp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitSimple_rexp(this);
		}
	}

	[RuleVersion(0)]
	public Simple_rexpContext simple_rexp() {
		Simple_rexpContext _localctx = new Simple_rexpContext(Context, State);
		EnterRule(_localctx, 14, RULE_simple_rexp);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 84;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 83; basic_rexp();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 86;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Basic_rexpContext : ParserRuleContext {
		public Star_rexpContext star_rexp() {
			return GetRuleContext<Star_rexpContext>(0);
		}
		public Plus_rexpContext plus_rexp() {
			return GetRuleContext<Plus_rexpContext>(0);
		}
		public Elementary_rexpContext elementary_rexp() {
			return GetRuleContext<Elementary_rexpContext>(0);
		}
		public Basic_rexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_basic_rexp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterBasic_rexp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitBasic_rexp(this);
		}
	}

	[RuleVersion(0)]
	public Basic_rexpContext basic_rexp() {
		Basic_rexpContext _localctx = new Basic_rexpContext(Context, State);
		EnterRule(_localctx, 16, RULE_basic_rexp);
		try {
			State = 91;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 88; star_rexp();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 89; plus_rexp();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 90; elementary_rexp();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Star_rexpContext : ParserRuleContext {
		public Elementary_rexpContext elementary_rexp() {
			return GetRuleContext<Elementary_rexpContext>(0);
		}
		public ITerminalNode STAR() { return GetToken(SpecParserParser.STAR, 0); }
		public Star_rexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_star_rexp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterStar_rexp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitStar_rexp(this);
		}
	}

	[RuleVersion(0)]
	public Star_rexpContext star_rexp() {
		Star_rexpContext _localctx = new Star_rexpContext(Context, State);
		EnterRule(_localctx, 18, RULE_star_rexp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93; elementary_rexp();
			State = 94; Match(STAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Plus_rexpContext : ParserRuleContext {
		public Elementary_rexpContext elementary_rexp() {
			return GetRuleContext<Elementary_rexpContext>(0);
		}
		public ITerminalNode PLUS() { return GetToken(SpecParserParser.PLUS, 0); }
		public Plus_rexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plus_rexp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterPlus_rexp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitPlus_rexp(this);
		}
	}

	[RuleVersion(0)]
	public Plus_rexpContext plus_rexp() {
		Plus_rexpContext _localctx = new Plus_rexpContext(Context, State);
		EnterRule(_localctx, 20, RULE_plus_rexp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96; elementary_rexp();
			State = 97; Match(PLUS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Elementary_rexpContext : ParserRuleContext {
		public Group_rexpContext group_rexp() {
			return GetRuleContext<Group_rexpContext>(0);
		}
		public BasicContext basic() {
			return GetRuleContext<BasicContext>(0);
		}
		public Elementary_rexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementary_rexp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterElementary_rexp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitElementary_rexp(this);
		}
	}

	[RuleVersion(0)]
	public Elementary_rexpContext elementary_rexp() {
		Elementary_rexpContext _localctx = new Elementary_rexpContext(Context, State);
		EnterRule(_localctx, 22, RULE_elementary_rexp);
		try {
			State = 101;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPEN_RE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 99; group_rexp();
				}
				break;
			case OPEN_PAREN:
			case OPEN_KLEENE_STAR_PAREN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 100; basic();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Group_rexpContext : ParserRuleContext {
		public ITerminalNode OPEN_RE() { return GetToken(SpecParserParser.OPEN_RE, 0); }
		public RexpContext rexp() {
			return GetRuleContext<RexpContext>(0);
		}
		public ITerminalNode CLOSE_RE() { return GetToken(SpecParserParser.CLOSE_RE, 0); }
		public Group_rexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_group_rexp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterGroup_rexp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitGroup_rexp(this);
		}
	}

	[RuleVersion(0)]
	public Group_rexpContext group_rexp() {
		Group_rexpContext _localctx = new Group_rexpContext(Context, State);
		EnterRule(_localctx, 24, RULE_group_rexp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103; Match(OPEN_RE);
			State = 104; rexp();
			State = 105; Match(CLOSE_RE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BasicContext : ParserRuleContext {
		public Simple_basicContext simple_basic() {
			return GetRuleContext<Simple_basicContext>(0);
		}
		public Kleene_star_basicContext kleene_star_basic() {
			return GetRuleContext<Kleene_star_basicContext>(0);
		}
		public BasicContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_basic; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterBasic(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitBasic(this);
		}
	}

	[RuleVersion(0)]
	public BasicContext basic() {
		BasicContext _localctx = new BasicContext(Context, State);
		EnterRule(_localctx, 26, RULE_basic);
		try {
			State = 109;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPEN_PAREN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 107; simple_basic();
				}
				break;
			case OPEN_KLEENE_STAR_PAREN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 108; kleene_star_basic();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Simple_basicContext : ParserRuleContext {
		public ITerminalNode OPEN_PAREN() { return GetToken(SpecParserParser.OPEN_PAREN, 0); }
		public Id_or_star_or_emptyContext id_or_star_or_empty() {
			return GetRuleContext<Id_or_star_or_emptyContext>(0);
		}
		public ITerminalNode CLOSE_PAREN() { return GetToken(SpecParserParser.CLOSE_PAREN, 0); }
		public MoreContext[] more() {
			return GetRuleContexts<MoreContext>();
		}
		public MoreContext more(int i) {
			return GetRuleContext<MoreContext>(i);
		}
		public Simple_basicContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simple_basic; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterSimple_basic(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitSimple_basic(this);
		}
	}

	[RuleVersion(0)]
	public Simple_basicContext simple_basic() {
		Simple_basicContext _localctx = new Simple_basicContext(Context, State);
		EnterRule(_localctx, 28, RULE_simple_basic);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 111; Match(OPEN_PAREN);
			State = 112; id_or_star_or_empty();
			State = 116;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OPEN_RE) | (1L << OPEN_PAREN) | (1L << OPEN_KLEENE_STAR_PAREN) | (1L << LCURLY) | (1L << LANG) | (1L << ID))) != 0)) {
				{
				{
				State = 113; more();
				}
				}
				State = 118;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 119; Match(CLOSE_PAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Kleene_star_basicContext : ParserRuleContext {
		public ITerminalNode OPEN_KLEENE_STAR_PAREN() { return GetToken(SpecParserParser.OPEN_KLEENE_STAR_PAREN, 0); }
		public Id_or_star_or_emptyContext id_or_star_or_empty() {
			return GetRuleContext<Id_or_star_or_emptyContext>(0);
		}
		public ITerminalNode CLOSE_KLEENE_STAR_PAREN() { return GetToken(SpecParserParser.CLOSE_KLEENE_STAR_PAREN, 0); }
		public MoreContext[] more() {
			return GetRuleContexts<MoreContext>();
		}
		public MoreContext more(int i) {
			return GetRuleContext<MoreContext>(i);
		}
		public Kleene_star_basicContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_kleene_star_basic; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterKleene_star_basic(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitKleene_star_basic(this);
		}
	}

	[RuleVersion(0)]
	public Kleene_star_basicContext kleene_star_basic() {
		Kleene_star_basicContext _localctx = new Kleene_star_basicContext(Context, State);
		EnterRule(_localctx, 30, RULE_kleene_star_basic);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 121; Match(OPEN_KLEENE_STAR_PAREN);
			State = 122; id_or_star_or_empty();
			State = 126;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OPEN_RE) | (1L << OPEN_PAREN) | (1L << OPEN_KLEENE_STAR_PAREN) | (1L << LCURLY) | (1L << LANG) | (1L << ID))) != 0)) {
				{
				{
				State = 123; more();
				}
				}
				State = 128;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 129; Match(CLOSE_KLEENE_STAR_PAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Id_or_star_or_emptyContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SpecParserParser.ID, 0); }
		public ITerminalNode STAR() { return GetToken(SpecParserParser.STAR, 0); }
		public Id_or_star_or_emptyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_id_or_star_or_empty; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterId_or_star_or_empty(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitId_or_star_or_empty(this);
		}
	}

	[RuleVersion(0)]
	public Id_or_star_or_emptyContext id_or_star_or_empty() {
		Id_or_star_or_emptyContext _localctx = new Id_or_star_or_emptyContext(Context, State);
		EnterRule(_localctx, 32, RULE_id_or_star_or_empty);
		try {
			State = 134;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 131; Match(ID);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 132; Match(STAR);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MoreContext : ParserRuleContext {
		public RexpContext rexp() {
			return GetRuleContext<RexpContext>(0);
		}
		public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public CodeContext code() {
			return GetRuleContext<CodeContext>(0);
		}
		public AttrContext attr() {
			return GetRuleContext<AttrContext>(0);
		}
		public MoreContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_more; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterMore(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitMore(this);
		}
	}

	[RuleVersion(0)]
	public MoreContext more() {
		MoreContext _localctx = new MoreContext(Context, State);
		EnterRule(_localctx, 34, RULE_more);
		try {
			State = 140;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPEN_RE:
			case OPEN_PAREN:
			case OPEN_KLEENE_STAR_PAREN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 136; rexp();
				}
				break;
			case LANG:
				EnterOuterAlt(_localctx, 2);
				{
				State = 137; text();
				}
				break;
			case LCURLY:
				EnterOuterAlt(_localctx, 3);
				{
				State = 138; code();
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 4);
				{
				State = 139; attr();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CodeContext : ParserRuleContext {
		public ITerminalNode LCURLY() { return GetToken(SpecParserParser.LCURLY, 0); }
		public ITerminalNode RCURLY() { return GetToken(SpecParserParser.RCURLY, 0); }
		public ITerminalNode[] OTHER() { return GetTokens(SpecParserParser.OTHER); }
		public ITerminalNode OTHER(int i) {
			return GetToken(SpecParserParser.OTHER, i);
		}
		public CodeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_code; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterCode(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitCode(this);
		}
	}

	[RuleVersion(0)]
	public CodeContext code() {
		CodeContext _localctx = new CodeContext(Context, State);
		EnterRule(_localctx, 36, RULE_code);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142; Match(LCURLY);
			State = 146;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OTHER) {
				{
				{
				State = 143; Match(OTHER);
				}
				}
				State = 148;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 149; Match(RCURLY);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextContext : ParserRuleContext {
		public ITerminalNode LANG() { return GetToken(SpecParserParser.LANG, 0); }
		public ITerminalNode RANG() { return GetToken(SpecParserParser.RANG, 0); }
		public ITerminalNode[] OTHER_ANG() { return GetTokens(SpecParserParser.OTHER_ANG); }
		public ITerminalNode OTHER_ANG(int i) {
			return GetToken(SpecParserParser.OTHER_ANG, i);
		}
		public TextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_text; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterText(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitText(this);
		}
	}

	[RuleVersion(0)]
	public TextContext text() {
		TextContext _localctx = new TextContext(Context, State);
		EnterRule(_localctx, 38, RULE_text);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151; Match(LANG);
			State = 155;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OTHER_ANG) {
				{
				{
				State = 152; Match(OTHER_ANG);
				}
				}
				State = 157;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 158; Match(RANG);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttrContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SpecParserParser.ID, 0); }
		public ITerminalNode EQ() { return GetToken(SpecParserParser.EQ, 0); }
		public ITerminalNode StringLiteral() { return GetToken(SpecParserParser.StringLiteral, 0); }
		public ITerminalNode STAR() { return GetToken(SpecParserParser.STAR, 0); }
		public AttrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attr; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterAttr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitAttr(this);
		}
	}

	[RuleVersion(0)]
	public AttrContext attr() {
		AttrContext _localctx = new AttrContext(Context, State);
		EnterRule(_localctx, 40, RULE_attr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 160; Match(ID);
			State = 161; Match(EQ);
			State = 162;
			_la = TokenStream.LA(1);
			if ( !(_la==STAR || _la==StringLiteral) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PassContext : ParserRuleContext {
		public ITerminalNode PASS() { return GetToken(SpecParserParser.PASS, 0); }
		public ITerminalNode ID() { return GetToken(SpecParserParser.ID, 0); }
		public ITerminalNode SEMI() { return GetToken(SpecParserParser.SEMI, 0); }
		public PassContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pass; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.EnterPass(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISpecParserListener typedListener = listener as ISpecParserListener;
			if (typedListener != null) typedListener.ExitPass(this);
		}
	}

	[RuleVersion(0)]
	public PassContext pass() {
		PassContext _localctx = new PassContext(Context, State);
		EnterRule(_localctx, 42, RULE_pass);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 164; Match(PASS);
			State = 165; Match(ID);
			State = 166; Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '.', '\xAB', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\a', 
		'\x2', '\x30', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '\x33', '\v', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '<', '\n', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\a', '\b', 'Q', '\n', '\b', '\f', '\b', 
		'\xE', '\b', 'T', '\v', '\b', '\x3', '\t', '\x6', '\t', 'W', '\n', '\t', 
		'\r', '\t', '\xE', '\t', 'X', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', 
		'\n', '^', '\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x5', '\r', 'h', 
		'\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x5', '\xF', 'p', '\n', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\a', '\x10', 'u', '\n', '\x10', '\f', '\x10', 
		'\xE', '\x10', 'x', '\v', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', '\x7F', '\n', '\x11', 
		'\f', '\x11', '\xE', '\x11', '\x82', '\v', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\x89', 
		'\n', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x5', '\x13', '\x8F', '\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\a', 
		'\x14', '\x93', '\n', '\x14', '\f', '\x14', '\xE', '\x14', '\x96', '\v', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\a', 
		'\x15', '\x9C', '\n', '\x15', '\f', '\x15', '\xE', '\x15', '\x9F', '\v', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x2', '\x2', '\x18', '\x2', '\x4', '\x6', '\b', 
		'\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', 
		'\x1E', ' ', '\"', '$', '&', '(', '*', ',', '\x2', '\x3', '\x4', '\x2', 
		'\x18', '\x18', '(', '(', '\x2', '\xA8', '\x2', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\x4', ';', '\x3', '\x2', '\x2', '\x2', '\x6', '=', '\x3', 
		'\x2', '\x2', '\x2', '\b', '\x41', '\x3', '\x2', '\x2', '\x2', '\n', '\x45', 
		'\x3', '\x2', '\x2', '\x2', '\f', 'I', '\x3', '\x2', '\x2', '\x2', '\xE', 
		'M', '\x3', '\x2', '\x2', '\x2', '\x10', 'V', '\x3', '\x2', '\x2', '\x2', 
		'\x12', ']', '\x3', '\x2', '\x2', '\x2', '\x14', '_', '\x3', '\x2', '\x2', 
		'\x2', '\x16', '\x62', '\x3', '\x2', '\x2', '\x2', '\x18', 'g', '\x3', 
		'\x2', '\x2', '\x2', '\x1A', 'i', '\x3', '\x2', '\x2', '\x2', '\x1C', 
		'o', '\x3', '\x2', '\x2', '\x2', '\x1E', 'q', '\x3', '\x2', '\x2', '\x2', 
		' ', '{', '\x3', '\x2', '\x2', '\x2', '\"', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '$', '\x8E', '\x3', '\x2', '\x2', '\x2', '&', '\x90', '\x3', '\x2', 
		'\x2', '\x2', '(', '\x99', '\x3', '\x2', '\x2', '\x2', '*', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', ',', '\xA6', '\x3', '\x2', '\x2', '\x2', '.', '\x30', 
		'\x5', '\x4', '\x3', '\x2', '/', '.', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x31', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x32', '\x3', '\x2', '\x2', '\x2', '\x32', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x31', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x35', '\a', '\x2', '\x2', '\x3', '\x35', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x36', '<', '\x5', '\x6', '\x4', '\x2', '\x37', '<', '\x5', '\b', 
		'\x5', '\x2', '\x38', '<', '\x5', '\n', '\x6', '\x2', '\x39', '<', '\x5', 
		'\f', '\a', '\x2', ':', '<', '\x5', ',', '\x17', '\x2', ';', '\x36', '\x3', 
		'\x2', '\x2', '\x2', ';', '\x37', '\x3', '\x2', '\x2', '\x2', ';', '\x38', 
		'\x3', '\x2', '\x2', '\x2', ';', '\x39', '\x3', '\x2', '\x2', '\x2', ';', 
		':', '\x3', '\x2', '\x2', '\x2', '<', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'=', '>', '\a', '\x13', '\x2', '\x2', '>', '?', '\a', '(', '\x2', '\x2', 
		'?', '@', '\a', '\x16', '\x2', '\x2', '@', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\x42', '\a', '\xE', '\x2', '\x2', '\x42', '\x43', '\a', 
		'(', '\x2', '\x2', '\x43', '\x44', '\a', '\x16', '\x2', '\x2', '\x44', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', '\v', '\x2', '\x2', 
		'\x46', 'G', '\a', '(', '\x2', '\x2', 'G', 'H', '\a', '\x16', '\x2', '\x2', 
		'H', '\v', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', '\x12', '\x2', 
		'\x2', 'J', 'K', '\x5', '\xE', '\b', '\x2', 'K', 'L', '\a', '\x16', '\x2', 
		'\x2', 'L', '\r', '\x3', '\x2', '\x2', '\x2', 'M', 'R', '\x5', '\x10', 
		'\t', '\x2', 'N', 'O', '\a', '\x17', '\x2', '\x2', 'O', 'Q', '\x5', '\x10', 
		'\t', '\x2', 'P', 'N', '\x3', '\x2', '\x2', '\x2', 'Q', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', 
		'\x2', '\x2', 'S', '\xF', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'W', '\x5', '\x12', '\n', '\x2', 'V', 'U', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 'V', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'Y', '\x3', '\x2', '\x2', '\x2', 'Y', '\x11', 
		'\x3', '\x2', '\x2', '\x2', 'Z', '^', '\x5', '\x14', '\v', '\x2', '[', 
		'^', '\x5', '\x16', '\f', '\x2', '\\', '^', '\x5', '\x18', '\r', '\x2', 
		']', 'Z', '\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', 
		']', '\\', '\x3', '\x2', '\x2', '\x2', '^', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '_', '`', '\x5', '\x18', '\r', '\x2', '`', '\x61', '\a', '\x18', 
		'\x2', '\x2', '\x61', '\x15', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\x5', '\x18', '\r', '\x2', '\x63', '\x64', '\a', '\x19', '\x2', '\x2', 
		'\x64', '\x17', '\x3', '\x2', '\x2', '\x2', '\x65', 'h', '\x5', '\x1A', 
		'\xE', '\x2', '\x66', 'h', '\x5', '\x1C', '\xF', '\x2', 'g', '\x65', '\x3', 
		'\x2', '\x2', '\x2', 'g', '\x66', '\x3', '\x2', '\x2', '\x2', 'h', '\x19', 
		'\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '\x1C', '\x2', '\x2', 'j', 
		'k', '\x5', '\xE', '\b', '\x2', 'k', 'l', '\a', '\x1D', '\x2', '\x2', 
		'l', '\x1B', '\x3', '\x2', '\x2', '\x2', 'm', 'p', '\x5', '\x1E', '\x10', 
		'\x2', 'n', 'p', '\x5', ' ', '\x11', '\x2', 'o', 'm', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'n', '\x3', '\x2', '\x2', '\x2', 'p', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', 'q', 'r', '\a', '\x1E', '\x2', '\x2', 'r', 'v', '\x5', '\"', 
		'\x12', '\x2', 's', 'u', '\x5', '$', '\x13', '\x2', 't', 's', '\x3', '\x2', 
		'\x2', '\x2', 'u', 'x', '\x3', '\x2', '\x2', '\x2', 'v', 't', '\x3', '\x2', 
		'\x2', '\x2', 'v', 'w', '\x3', '\x2', '\x2', '\x2', 'w', 'y', '\x3', '\x2', 
		'\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', '\x1F', 
		'\x2', '\x2', 'z', '\x1F', '\x3', '\x2', '\x2', '\x2', '{', '|', '\a', 
		' ', '\x2', '\x2', '|', '\x80', '\x5', '\"', '\x12', '\x2', '}', '\x7F', 
		'\x5', '$', '\x13', '\x2', '~', '}', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x80', '~', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '\x81', '\x3', '\x2', '\x2', '\x2', '\x81', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', '\x2', '\x2', '\x83', 
		'\x84', '\a', '!', '\x2', '\x2', '\x84', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x85', '\x89', '\a', ')', '\x2', '\x2', '\x86', '\x89', '\a', '\x18', 
		'\x2', '\x2', '\x87', '\x89', '\x3', '\x2', '\x2', '\x2', '\x88', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '\x88', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'\x88', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x8A', '\x8F', '\x5', '\xE', '\b', '\x2', '\x8B', '\x8F', 
		'\x5', '(', '\x15', '\x2', '\x8C', '\x8F', '\x5', '&', '\x14', '\x2', 
		'\x8D', '\x8F', '\x5', '*', '\x16', '\x2', '\x8E', '\x8A', '\x3', '\x2', 
		'\x2', '\x2', '\x8E', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8C', 
		'\x3', '\x2', '\x2', '\x2', '\x8E', '\x8D', '\x3', '\x2', '\x2', '\x2', 
		'\x8F', '%', '\x3', '\x2', '\x2', '\x2', '\x90', '\x94', '\a', '&', '\x2', 
		'\x2', '\x91', '\x93', '\a', ',', '\x2', '\x2', '\x92', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x96', '\x3', '\x2', '\x2', '\x2', '\x94', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x97', '\x3', '\x2', '\x2', '\x2', '\x96', '\x94', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x98', '\a', '+', '\x2', '\x2', '\x98', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9D', '\a', '\'', '\x2', '\x2', 
		'\x9A', '\x9C', '\a', '.', '\x2', '\x2', '\x9B', '\x9A', '\x3', '\x2', 
		'\x2', '\x2', '\x9C', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9B', 
		'\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', '\x2', 
		'\x9E', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x9F', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '\xA0', '\xA1', '\a', '-', '\x2', '\x2', '\xA1', ')', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', ')', '\x2', '\x2', '\xA3', 
		'\xA4', '\a', '\x15', '\x2', '\x2', '\xA4', '\xA5', '\t', '\x2', '\x2', 
		'\x2', '\xA5', '+', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\a', 
		'\x10', '\x2', '\x2', '\xA7', '\xA8', '\a', ')', '\x2', '\x2', '\xA8', 
		'\xA9', '\a', '\x16', '\x2', '\x2', '\xA9', '-', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '\x31', ';', 'R', 'X', ']', 'g', 'o', 'v', '\x80', '\x88', 
		'\x8E', '\x94', '\x9D',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
