
/usr/bin/cc \
	-Wall \
	-fno-exceptions \
	-fno-rtti \
	-DClangCode_EXPORTS \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/llvm/tools/clang/include \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/tools/clang/include \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/llvm/include \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/include \
	-std=c++11 \
	-O3 \
	-DNDEBUG \
	-fPIC \
	-D_GNU_SOURCE \
	-D_DEBUG \
	-D__STDC_CONSTANT_MACROS \
	-D__STDC_FORMAT_MACROS \
	-D__STDC_LIMIT_MACROS \
	-o Source3.o \
	-c \
	Source3.c
	
/usr/bin/c++ \
	-Wall \
	-fno-exceptions \
	-fno-rtti \
	-DClangCode_EXPORTS \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/llvm/tools/clang/include \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/tools/clang/include \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/llvm/include \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/include \
	-std=c++11 \
	-O3 \
	-DNDEBUG \
	-fPIC \
	-D_GNU_SOURCE \
	-D_DEBUG \
	-D__STDC_CONSTANT_MACROS \
	-D__STDC_FORMAT_MACROS \
	-D__STDC_LIMIT_MACROS \
	-o Source.o \
	-c \
	Source.c
	
/usr/bin/c++ \
	-Wall \
	-fno-exceptions \
	-fno-rtti \
	-DClangCode_EXPORTS \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/llvm/tools/clang/include \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/tools/clang/include \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/llvm/include \
	-I/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/include \
	-std=c++11 \
	-O3 \
	-DNDEBUG \
	-fPIC \
	-D_GNU_SOURCE \
	-D_DEBUG \
	-D__STDC_CONSTANT_MACROS \
	-D__STDC_FORMAT_MACROS \
	-D__STDC_LIMIT_MACROS \
	-o Source2.o \
	-c \
	Source2.c
	
#	-fvisibility-inlines-hidden

/usr/bin/c++ \
	-fvisibility=default \
	-fPIC \
	-Werror=date-time \
	-std=c++11 \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-Wwrite-strings \
	-Wcast-qual \
	-Wno-missing-field-initializers \
	-pedantic \
	-Wno-long-long \
	-Wno-maybe-uninitialized \
	-Wdelete-non-virtual-dtor \
	-Wno-comment \
	-fno-common \
	-Woverloaded-virtual \
	-fno-strict-aliasing \
	-g  \
	-Wl,-rpath-link,/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/./lib   \
	-Wl,-z,defs \
	-Wl,-z,nodelete \
	-shared \
	-Wl,-soname,ClangCode.so \
	-o ClangCode.so \
	Source.o \
	Source2.o \
	Source3.o \
	-Wl,-rpath,"\$ORIGIN/../lib" \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangAST.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangBasic.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangFrontend.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangIndex.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangLex.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangQuery.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangSema.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTooling.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangARCMigrate.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyPlugin.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangIncludeFixerPlugin.a \
	-ldl \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64CodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64AsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64AsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64Desc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64Disassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64Info.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64Utils.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUAsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUUtils.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMAsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMUtils.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMBPFCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMBPFAsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMBPFAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMBPFDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMBPFDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMBPFInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMHexagonCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMHexagonAsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMHexagonDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMHexagonDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMHexagonInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMLanaiCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMLanaiAsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMLanaiAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMLanaiDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMLanaiDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMLanaiInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMipsCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMipsAsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMipsAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMipsDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMipsDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMipsInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMSP430CodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMSP430AsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMSP430Desc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMSP430Info.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMNVPTXCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMNVPTXAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMNVPTXDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMNVPTXInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMPowerPCCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMPowerPCAsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMPowerPCAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMPowerPCDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMPowerPCDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMPowerPCInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSparcCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSparcAsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSparcAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSparcDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSparcDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSparcInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSystemZCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSystemZAsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSystemZAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSystemZDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSystemZDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSystemZInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMX86CodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMX86AsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMX86AsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMX86Desc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMX86Disassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMX86Info.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMX86Utils.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMXCoreCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMXCoreAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMXCoreDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMXCoreDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMXCoreInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMCore.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSupport.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyAbseilModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyAndroidModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyBoostModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyCERTModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyFuchsiaModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyHICPPModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyBugproneModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyCppCoreGuidelinesModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyGoogleModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyLLVMModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyMiscModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyModernizeModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyMPIModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyObjCModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyPerformanceModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyPortabilityModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyReadabilityModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyZirconModule.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidyUtils.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTidy.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangStaticAnalyzerFrontend.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangStaticAnalyzerCheckers.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangStaticAnalyzerCore.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangCrossTU.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangIndex.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangIncludeFixer.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libfindAllSymbols.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangTooling.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangFrontend.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangParse.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangSerialization.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangSema.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangEdit.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangAnalysis.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangDriver.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMOption.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangFormat.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangToolingInclusions.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangToolingCore.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangRewrite.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangASTMatchers.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangAST.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangLex.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libclangBasic.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64Desc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64AsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64Info.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAArch64Utils.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAMDGPUUtils.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMARMUtils.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMBPFAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMHexagonDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMHexagonInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMLanaiDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMLanaiAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMLanaiInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMipsAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMSP430AsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMNVPTXAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMipo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMVectorize.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMIRReader.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAsmParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMInstrumentation.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMLinker.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMPowerPCAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSparcAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSystemZDesc.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSystemZAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSystemZInfo.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMGlobalISel.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMX86AsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMX86Utils.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMXCoreAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAsmPrinter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSelectionDAG.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMCodeGen.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMScalarOpts.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAggressiveInstCombine.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMInstCombine.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMBitWriter.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMTarget.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMTransformUtils.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMAnalysis.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMProfileData.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMObject.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMBitReader.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMCore.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMCParser.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMCDisassembler.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMMC.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMBinaryFormat.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMDebugInfoCodeView.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMDebugInfoMSF.a \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMSupport.a \
	-lz \
	-lrt \
	-ldl \
	-ltinfo \
	-lpthread \
	-lm \
	-lstdc++fs \
	/mnt/c/Users/Kenne/Documents/clang-llvm/build-linux/lib/libLLVMDemangle.a 
