
# /usr/bin/clang++-3.9  -DAMD64 -DBIT64=1 -DBUILDENV_CHECKED=1 -DDACCESS_COMPILE -DDBG_TARGET_64BIT=1 -DDBG_TARGET_AMD64=1 -DDBG_TARGET_AMD64_UNIX -DDBG_TARGET_WIN64=1 -DDEBUG -DDEBUGGING_SUPPORTED -DDISABLE_CONTRACTS -DFEATURE_ARRAYSTUB_AS_IL -DFEATURE_CODE_VERSIONING -DFEATURE_COLLECTIBLE_TYPES -DFEATURE_CORECLR -DFEATURE_CORESYSTEM -DFEATURE_CORRUPTING_EXCEPTIONS -DFEATURE_DBGIPC_TRANSPORT_DI -DFEATURE_DBGIPC_TRANSPORT_VM -DFEATURE_DEFAULT_INTERFACES=1 -DFEATURE_EVENTSOURCE_XPLAT=1 -DFEATURE_EVENT_TRACE=1 -DFEATURE_HIJACK -DFEATURE_ICASTABLE -DFEATURE_ISYM_READER -DFEATURE_JUMPSTAMP -DFEATURE_LEGACYNETCF_DBG_HOST_CONTROL -DFEATURE_MANAGED_ETW -DFEATURE_MANAGED_ETW_CHANNELS -DFEATURE_MANUALLY_MANAGED_CARD_BUNDLES -DFEATURE_MULTICASTSTUB_AS_IL -DFEATURE_MULTICOREJIT -DFEATURE_MULTIREG_RETURN -DFEATURE_PAL -DFEATURE_PAL_ANSI -DFEATURE_PAL_SXS -DFEATURE_PERFMAP -DFEATURE_PERFTRACING=1 -DFEATURE_PREJIT -DFEATURE_READYTORUN -DFEATURE_REJIT -DFEATURE_STANDALONE_GC -DFEATURE_STANDALONE_SN -DFEATURE_STRONGNAME_DELAY_SIGNING_ALLOWED -DFEATURE_STRONGNAME_MIGRATION -DFEATURE_STUBS_AS_IL -DFEATURE_SVR_GC -DFEATURE_SYMDIFF -DFEATURE_TIERED_COMPILATION -DFEATURE_USE_ASM_GC_WRITE_BARRIERS -DFEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP -DFEATURE_WINDOWSPHONE -DFEATURE_WINMD_RESILIENT -DLINUX64 -DPLATFORM_UNIX=1 -DPROFILING_SUPPORTED_DATA -DUNICODE -DUNIX_AMD64_ABI -DUNIX_AMD64_ABI_ITF -DURTBLDENV_FRIENDLY=Checked -DWRITE_BARRIER_CHECK=1 -D_AMD64_ -D_BLD_CLR -D_DBG -D_DEBUG -D_SECURE_SCL=0 -D_TARGET_64BIT_=1 -D_TARGET_AMD64_=1 -D_UNICODE -D_WIN64 -I/mnt/c/Users/Kenne/Documents/coreclr/bin/obj/Linux.x64.Debug/src/vm/dac -I/mnt/c/Users/Kenne/Documents/coreclr/src/vm/dac -I/mnt/c/Users/Kenne/Documents/coreclr/src/vm -I/mnt/c/Users/Kenne/Documents/coreclr/src/pal/prebuilt/inc -I/mnt/c/Users/Kenne/Documents/coreclr/bin/obj -I/mnt/c/Users/Kenne/Documents/coreclr/src/pal/inc -I/mnt/c/Users/Kenne/Documents/coreclr/src/pal/inc/rt -I/mnt/c/Users/Kenne/Documents/coreclr/src/pal/src/safecrt -I/mnt/c/Users/Kenne/Documents/coreclr/src/inc -I/mnt/c/Users/Kenne/Documents/coreclr/src/strongname/inc -I/mnt/c/Users/Kenne/Documents/coreclr/src/inc/winrt -I/mnt/c/Users/Kenne/Documents/coreclr/src/debug/inc -I/mnt/c/Users/Kenne/Documents/coreclr/src/debug/inc/amd64 -I/mnt/c/Users/Kenne/Documents/coreclr/src/debug/inc/dump -I/mnt/c/Users/Kenne/Documents/coreclr/src/md/inc -I/mnt/c/Users/Kenne/Documents/coreclr/src/classlibnative/bcltype -I/mnt/c/Users/Kenne/Documents/coreclr/src/classlibnative/cryptography -I/mnt/c/Users/Kenne/Documents/coreclr/src/classlibnative/inc -I/mnt/c/Users/Kenne/Documents/coreclr/bin/obj/Linux.x64.Debug/src/inc -I/mnt/c/Users/Kenne/Documents/coreclr/src/pal/inc/rt/cpp -I/mnt/c/Users/Kenne/Documents/coreclr/src/nativeresources -I/mnt/c/Users/Kenne/Documents/coreclr/src/vm/amd64  -Wall -Wno-null-conversion -std=c++11 -g -O0   -fno-omit-frame-pointer -fms-extensions -fwrapv -fstack-protector-strong -ferror-limit=4096 -Werror -Wno-unused-private-field -Wno-unused-variable -Wno-microsoft -Wno-tautological-compare -Wno-constant-logical-operand -Wno-pragma-pack -Wno-unknown-warning-option -Wno-invalid-offsetof -Wno-incompatible-ms-struct -fsigned-char -nostdinc -fPIC -o CMakeFiles/cee_dac.dir/__/peimage.cpp.o -c /mnt/c/Users/Kenne/Documents/coreclr/src/vm/peimage.cpp

/mnt/c/Users/Kenne/Documents/Piggy3/ClangSerializer/bin/Debug/netcoreapp2.1/ubuntu.18.04-x64/publish/ClangSerializer \
 -c \
	DAMD64 \
	DBIT64=1 \
	DBUILDENV_CHECKED=1 \
	DDACCESS_COMPILE \
	DDBG_TARGET_64BIT=1 \
	DDBG_TARGET_AMD64=1 \
	DDBG_TARGET_AMD64_UNIX \
	DDBG_TARGET_WIN64=1 \
	DDEBUG \
	DDEBUGGING_SUPPORTED \
	DDISABLE_CONTRACTS \
	DFEATURE_ARRAYSTUB_AS_IL \
	DFEATURE_CODE_VERSIONING \
	DFEATURE_COLLECTIBLE_TYPES \
	DFEATURE_CORECLR \
	DFEATURE_CORESYSTEM \
	DFEATURE_CORRUPTING_EXCEPTIONS \
	DFEATURE_DBGIPC_TRANSPORT_DI \
	DFEATURE_DBGIPC_TRANSPORT_VM \
	DFEATURE_DEFAULT_INTERFACES=1 \
	DFEATURE_EVENTSOURCE_XPLAT=1 \
	DFEATURE_EVENT_TRACE=1 \
	DFEATURE_HIJACK \
	DFEATURE_ICASTABLE \
	DFEATURE_ISYM_READER \
	DFEATURE_JUMPSTAMP \
	DFEATURE_LEGACYNETCF_DBG_HOST_CONTROL \
	DFEATURE_MANAGED_ETW \
	DFEATURE_MANAGED_ETW_CHANNELS \
	DFEATURE_MANUALLY_MANAGED_CARD_BUNDLES \
	DFEATURE_MULTICASTSTUB_AS_IL \
	DFEATURE_MULTICOREJIT \
	DFEATURE_MULTIREG_RETURN \
	DFEATURE_PAL \
	DFEATURE_PAL_ANSI \
	DFEATURE_PAL_SXS \
	DFEATURE_PERFMAP \
	DFEATURE_PERFTRACING=1 \
	DFEATURE_PREJIT \
	DFEATURE_READYTORUN \
	DFEATURE_REJIT \
	DFEATURE_STANDALONE_GC \
	DFEATURE_STANDALONE_SN \
	DFEATURE_STRONGNAME_DELAY_SIGNING_ALLOWED \
	DFEATURE_STRONGNAME_MIGRATION \
	DFEATURE_STUBS_AS_IL \
	DFEATURE_SVR_GC \
	DFEATURE_SYMDIFF \
	DFEATURE_TIERED_COMPILATION \
	DFEATURE_USE_ASM_GC_WRITE_BARRIERS \
	DFEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP \
	DFEATURE_WINDOWSPHONE \
	DFEATURE_WINMD_RESILIENT \
	DLINUX64 \
	DPLATFORM_UNIX=1 \
	DPROFILING_SUPPORTED_DATA \
	DUNICODE \
	DUNIX_AMD64_ABI \
	DUNIX_AMD64_ABI_ITF \
	DURTBLDENV_FRIENDLY=Checked \
	DWRITE_BARRIER_CHECK=1 \
	D_AMD64_ \
	D_BLD_CLR \
	D_DBG \
	D_DEBUG \
	D_SECURE_SCL=0 \
	D_TARGET_64BIT_=1 \
	D_TARGET_AMD64_=1 \
	D_UNICODE \
	D_WIN64 \
	I/mnt/c/Users/Kenne/Documents/coreclr/bin/obj/Linux.x64.Debug/src/vm/dac \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/vm/dac \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/vm \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/pal/prebuilt/inc \
	I/mnt/c/Users/Kenne/Documents/coreclr/bin/obj \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/pal/inc \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/pal/inc/rt \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/pal/src/safecrt \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/inc \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/strongname/inc \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/inc/winrt \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/debug/inc \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/debug/inc/amd64 \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/debug/inc/dump \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/md/inc \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/classlibnative/bcltype \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/classlibnative/cryptography \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/classlibnative/inc \
	I/mnt/c/Users/Kenne/Documents/coreclr/bin/obj/Linux.x64.Debug/src/inc \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/pal/inc/rt/cpp \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/nativeresources \
	I/mnt/c/Users/Kenne/Documents/coreclr/src/vm/amd64 \
	Wall \
	Wno-null-conversion \
	std=c++11 \
	g \
	O0 \
	fno-omit-frame-pointer \
	fms-extensions \
	fwrapv \
	fstack-protector-strong \
	ferror-limit=4096 \
	Werror \
	Wno-unused-private-field \
	Wno-unused-variable \
	Wno-microsoft \
	Wno-tautological-compare \
	Wno-constant-logical-operand \
	Wno-pragma-pack \
	Wno-unknown-warning-option \
	Wno-invalid-offsetof \
	Wno-incompatible-ms-struct \
	fsigned-char \
	nostdinc \
	fPIC \
 -f \
	/mnt/c/Users/Kenne/Documents/coreclr/src/vm/peimage.cpp \
 -o ast.ast
 